%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Author: Jagannathan Chakravarthy

%Purpose: This code will separate the foreground from a Video taken from a
%non-moving camera. The background is initally generated by the
%background.m file which is used here to separate the foreground
%The foreground image is stored as foreground.jpg.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all;
clc;
% Input frames with VideoReader

inputObj = VideoReader('video.mp4')
nFrames = inputObj.NumberOfFrames;

%first frame as the back-frame
back_frame = imread('background.jpg');
[x,y] = size(back_frame);
fore_frame = read(inputObj,1);
fore_frame1 = rgb2gray(fore_frame);
diff = abs (double(fore_frame1) - double(back_frame));

forg = zeros(x,y);

%get the foreground from the first frame
for i=1:x
        for j=1:y
            if (diff(i,j)>50)
                forg(i,j) = fore_frame1(i,j);
            else
                forg(i,j) = 0;
            end
        end
end

fg_filt = medfilt2(forg, [4,4]);
imshow(uint8(fg_filt));

%store the background
imwrite(uint8(fg_filt), 'foreground.jpg');